---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: Amazon FSX for NetApp ONTAP 的文件
    url: "/index.html"
  - title: 版本資訊
    url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 瞭解Amazon FSX for NetApp ONTAP 的功能
      url: "/start/concept-fsx-aws.html"
    - title: 快速入門
      url: "/start/task-getting-started-fsx.html"
  - title: 需求
    entries:
    - title: 設定權限
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: 安全性群組規則
      url: "/requirements/reference-security-groups-fsx.html"
  - title: 使用Amazon FSX for NetApp ONTAP 解決方案
    entries:
    - title: 建立或探索工作環境
      url: "/use/task-creating-fsx-working-environment.html"
    - title: 管理工作環境
      url: "/use/task-manage-working-environment.html"
    - title: 建立及掛載 Volume
      url: "/use/task-add-fsx-volumes.html"
    - title: 管理磁碟區
      url: "/use/task-manage-fsx-volumes.html"
    - title: 新增及管理儲存 VM
      url: "/use/task-add-fsx-svm.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/support/task-support-registration.html"
    - title: 取得協助
      url: "/support/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
