---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSX for NetApp ONTAP 是一項完全託管的服務、可讓客戶啟動及執行 NetApp ONTAP 儲存作業系統所支援的檔案系統。 
---
= 瞭解Amazon FSX for NetApp ONTAP 的功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 產品"^] 是一項完全託管的服務、可讓客戶啟動及執行 NetApp ONTAP 儲存作業系統所支援的檔案系統。FSX for ONTAP VMware提供NetApp客戶在內部部署所使用的相同功能、效能和管理功能、以及原生AWS服務的簡易性、敏捷度、安全性和擴充性。



== 在 BlueXP  中使用適用於 ONTAP 的 FSX

從 BlueXP  畫布中，您可以建立和探索適用於 ONTAP 工作環境的 FSX ，並使用系統管理員和其他 BlueXP  服務。如果您想要管理在 Amazon FSX for NetApp ONTAP 上執行的 ONTAP 工作環境和工作負載的 FSX ，請使用 https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["BlueXP  工作負載工廠"^]。

link:../use/task-creating-fsx-working-environment.html["瞭解如何在 BlueXP  中建立及探索適用於 ONTAP 工作環境的 FSX"^]。



== 功能

* 無需設定或管理儲存設備、軟體或備份。
* 支援 CIFS 、 iSCSI 、 NFSv3 、 NFSv4.x https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["S3"^] 及 SMB v2.0 - v3.1.1 傳輸協定。
* 使用不常存取（IA）的可用儲存層、以低成本、幾乎不受限制的方式儲存資料容量。
* 通過認證、可在對延遲敏感的應用程式（包括Oracle RAC）上執行。
* 可選擇搭售和隨用隨付定價。




== BlueXP的其他功能

* 在 _Standard_ 模式下使用 BlueXP  時，支援適用於 ONTAP 的 FSX ，此模式利用 BlueXP  SaaS 層來提供完整功能。不支援 _Restricted 模式和 _Private 模式。
+
請參閱 link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP 部署模式"^] 以取得更多資訊。

* 使用 link:https://docs.netapp.com/us-en/bluexp-family/["藍圖"^] 此外、 AWS 中的 Connector 還能建立和管理磁碟區、複寫資料、並將適用於 ONTAP 的 FSX 與 NetApp 雲端服務整合、例如 BlueXP 分類和 BlueXP 複製與同步。
* BlueXP 分類採用人工智慧（ AI ）導向技術、可協助您瞭解資料內容、並識別位於 ONTAP 帳戶的 FSX 中的敏感資料。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["深入瞭解"^]。
* 使用 BlueXP 複製與同步、您可以將資料移轉至雲端或內部部署的任何目標自動化。 https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["深入瞭解"^]




== 連接器和連結可解除鎖定所有適用於 ONTAP 功能的 FSX

連接器和連結可在 BlueXP  和 Amazon FSX 之間建立連線，並建立信任關係，以利 NetApp ONTAP 工作環境。BlueXP  Connector 是在雲端或內部部署網路中執行的 NetApp 軟體，而連結則使用 AWS Lambda 來執行 NetApp 程式碼。您不需要連接器或連結即可開始使用 BlueXP  或為 ONTAP 工作環境建立 FSX ，但您需要使用連接器或連結來充分利用適用於 ONTAP 功能的 FSX 。

您需要連接器或連結才能使用下列功能：

* 顯示安裝在適用於 ONTAP 檔案系統的 FSX 上的 ONTAP 版本
* 管理系統上的 iSCSI 磁碟區
* 啟用和停用 Volume 的自動擴充功能
* 建立及管理快照原則
* 設定複寫關係、並在檔案系統之間複寫磁碟區
* 設定備份關係、並將 Volume 資料備份至雲端儲存設備
* 在檔案系統中複製磁碟區
* 直接從 ONTAP 顯示其他指標（ Amazon CloudWatch 會收集預設指標）
* NFS 匯出原則的管理


深入瞭解連接器和連結，以及何時應使用這些連結：

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["深入瞭解連接器"^]。
* https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["深入瞭解連結"^]。




== 成本

您的FSX for ONTAP Sfor Sf堅持 帳戶是由AWS維護、而非由BlueXP維護。請參閱 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 《入門指南》"^]。

在 AWS 中使用 Connector 和選用的資料服務（例如 BlueXP 複製與同步和 BlueXP 分類）會產生額外成本。



== 支援的地區

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["檢視支援的Amazon地區。"^]



== 取得協助

Amazon FSX for NetApp ONTAP 的功能是AWS的第一方解決方案。如需與適用於 ONTAP 檔案系統、基礎架構或任何使用此服務的解決方案的 FSX 相關的問題或技術支援問題、請使用 AWS 管理主控台的支援中心、開啟 AWS 的支援案例。選取「適用於 ONTAP 的 FSX 」服務和適當類別。提供建立AWS支援案例所需的其餘資訊。

如需有關BlueXP或BlueXP儲存解決方案與服務的一般問題、請從線上的BlueXP聊天開始。

如需特定於 BlueXP  或 BlueXP  儲存解決方案與服務的技術支援問題、您可以使用 BlueXP  組織層級序號來開啟 NetApp 支援服務單。您需要link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["註冊您的 BlueXP  組織"^]啟動支援。
